### ISSUE TITLE
a problem on circexplorer2

### ISSUE THREAD

**Issue by noahpieta** [YangLab/CIRCexplorer2#1]
hello! i have got a problem on circexplore2. i have tried to install circexplore2 by pip or conda sucessfully. but an error as below disappeared when i run CIRCexplore2,

![circexplorer2_error](https://cloud.githubusercontent.com/assets/9362155/16551856/27c59a00-41ef-11e6-95c5-86771c58d63a.JPG)

i have tried to reinstall all the modules but it still do not work. would you help me to solve it?
THANK YOU very much!

**Comment by kepbod** [comment]
I think this bug is derived from [bioconda recipes](https://github.com/bioconda/bioconda-recipes), and we are working on it to fix this bug. You could try install CIRCexplorer2 via pip first.

**Comment by noahpieta** [comment]
i have tried both pip and from source code too. same problem has been encounted.
![circ_error2](https://cloud.githubusercontent.com/assets/9362155/16552870/f4e87afa-41f6-11e6-8a0b-0ca0d8c8d412.JPG)

**Comment by kepbod** [comment]
Because you have not removed all the stuffs from bioconda installation, and there are some contaminations from bioconda. You should clean up your installation environment, then install CIRCexplorer2 via pip.

**Comment by kepbod** [comment]
We found out where the bug is. Because you have installed the CIRCexplorer before, and CIRCexplorer2 uses the same module name (circ) with CIRCexplorer. So CIRCexplorer2 searches for the wrong path of circ module. Now for this version (2.0.1), you could delete CIRCexplorer first, and then install CIRCexplorer2. We will fix this bug in the next version.

**Comment by noahpieta** [comment]
yeap! it works!!!! thank you very much!!!!

**Comment by sszhou** [comment]
Hey guys, I'm not quite sure how was I added to the group and why do I keep getting emails from y'all. I guess you probably have added the wrong team member?

Cheers
Shanshan

Sent from my iPad

On 4/07/2016, at 19:40, Xiao-Ou Zhang <notifications@github.com<mailto:notifications@github.com>> wrote:

we found out where the bug is. Because you have installed the CIRCexplorer before, and CIRCexplorer2 uses the same module name (circ) with CIRCexplorer. So CIRCexplorer2 searches for the wrong path of circ module. Now for this version, you could delete CIRCexplorer first, and then install CIRCexplorer2. We will fix this bug in the next version.

##
