### ISSUE TITLE
Apparent problem with pybedtools binaries after PIP download 

### ISSUE THREAD

**Issue by illWill** [YangLab/CIRCexplorer2#18]
I ran the following command: 

CIRCexplorer2 align -G ~/Genomes/mm9/txome/mm9.gtf -g ~/Genomes/mm9/mm9.all.fa -i ~/Genomes/mm9/mm9 -j ~/Genomes/mm9/mm9.b2 -f Topotecan_riboZero_GST01_GTCCGC_L001_Rep1_1.txt.fq -o Tecan1_1 -b Tecan1_1.bed

with the following error:

Traceback (most recent call last):
  File "/PHShome/wrj2/anaconda2/bin/CIRCexplorer2", line 11, in <module>
    load_entry_point('CIRCexplorer2==2.3.3', 'console_scripts', 'CIRCexplorer2')()
  File "build/bdist.linux-x86_64/egg/circ2/command_parse.py", line 41, in main
  File "build/bdist.linux-x86_64/egg/circ2/align.py", line 28, in <module>
  File "/PHShome/wrj2/anaconda2/lib/python2.7/site-packages/pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (Interval, IntervalFile, overlap, Attributes,
ImportError: /PHShome/wrj2/anaconda2/lib/python2.7/site-packages/pybedtools/cbedtools.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

The error appears to be in the pybedtools binaries, perhaps. My install both using "pip install" and, after pip uninstalling, from the source code both failed in this way.

**Comment by kepbod** [comment]
This problem is out of the scope of CIRCexplorer2, so I closed this issue. According to other similar issues (https://github.com/masashi-y/depccg/issues/4, https://github.com/explosion/spaCy/issues/819, https://github.com/dib-lab/sourmash/issues/26), it may be derived from the g++ in your computer. I am not sure whether it would be help if you reinstall your g++ compiler.
