### ISSUE TITLE
Is it possible to use assemble function with STAR output?

### ISSUE THREAD

**Issue by qoiopipq** [YangLab/CIRCexplorer2#19]
Hi,

I used STAR to align my paired-end reads and followed the pipeline from 'Align-Parse-Annotate'. I got a list of predicted circRNAs that perfectly match with annotated genes. The results looked pretty good for these known circRNAs. 

However, when I visualised STAR chimeric.bam file in UCSC genome browser, some circRNAs with reasonable back-splicing junction reads were not included in the output from the Annotate step. It's simply because splice sites do not match with the reference or the back-splicing junctions are on the anti-sense strand. 

I read that CIRCexplorer2 assemble function requires Tophat/Cufflinks and it's recommended to use Tophat/Tophat-fusion. Since Tophat is under low-maintenance and I want to be consistent using same aligner to identify both known and novel circRNAs.  I'm wondering is it possible to use CIRCexplorer2 assemble function with STAR output to identify novel circRNAs? Or are there any alternative methods to extract those novel circRNAs with number of junction reads from STAR output?

Thanks

**Comment by kepbod** [comment]
Currently there are two ways to extract novel circRNAs from STAR output. One way is to directly use the parse results from Chimeric.out.junction (http://circexplorer2.readthedocs.io/en/latest/tutorial/parsing/), and it will include all the reads in a circular form. It may contain some false positives because we did not align their coordinates to gene annotations, but it would include all the novel ones. The second way is to add --low-confidence or --no-fix in the annotate step (http://circexplorer2.readthedocs.io/en/latest/modules/annotate/), and it would include some novel circRNAs. To be noted, we could not assure the high accuracy if you use those methods.
