### ISSUE TITLE
Error: cannot convert GenePred to GTF!

### ISSUE THREAD

**Issue by sambhav2mishra** [YangLab/CIRCexplorer2#35]
Dear kepbod / Xingma
I'm struck in assembling of circRNA transcripts and it gives me this error below:

**genePredToGtf: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
Error: cannot convert GenePred to GTF!**

**my command :**
CIRCexplorer2 assemble -p 30 -r hg38_refFlat.txt -m /userdata/Dramaresh/circ_explorer/tophat_hela_cell/SRR5122011alignment/tophat -o SRR5122011assemble > SRR5122011CIRCexplorer2_assemble.log

**Comment by kepbod** [comment]
This is the problem of `genePredToGtf`. Please try to reinstall it.

**Comment by kepbod** [comment]
We welcome and appreciate all the suggestions and bug reports for CIRCexplorer2. All your reported issues are due to the incorrect configuration of different aligners/tools, and none of them are derived from CIRCexplorer2. I suggested that you could reinstall all the related softwares and configure them correctly. If you could not figure out what is wrong with your configure, you could try [bioconda](https://bioconda.github.io/) to install them from scratch.
